services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./hire-link-be
    container_name: hire-link-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/jobportal

  frontend:
    build:
      context: ./hire-link-fe
    container_name: hire-link-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
